name: ASN1Kit
options:
  bundleIdPrefix: de.gematik.ti.common
  deploymentTarget:
    macOS: 11.0
    iOS: 12.1
settings:
  base:
    VERSIONING_SYSTEM: "apple-generic"
    CURRENT_PROJECT_VERSION: -1
    SWIFT_VERSION: 5.0
    ALWAYS_SEARCH_USER_PATHS: NO
    BUILD_LIBRARY_FOR_DISTRIBUTION: YES
  configs:
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
    Debug:
      SWIFT_COMPILATION_MODE: incremental
targets:
  ASN1Kit:
    type: framework
    platform: [macOS, iOS]
    info:
      path: Resources/ASN1Kit_Info.plist
    sources:
      - Sources/ASN1Kit
    dependencies:
      - framework: Carthage/Build/GemCommonsKit.xcframework
      - framework: Carthage/Build/DataKit.xcframework
    scheme:
      testTargets:
        - ASN1KitTests_${platform}
      gatherCoverageData: true
  asn1c:
    type: tool
    platform: macOS
    settings:
        base:
            SWIFT_FORCE_DYNAMIC_LINK_STDLIB: YES
            SWIFT_FORCE_STATIC_LINK_STDLIB: NO
            LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path"
    sources:
      - Sources/CLI
    dependencies:
      - target: ASN1Kit_macOS
        embed: true
      - framework: Carthage/Build/Commandant.xcframework
      - framework: Carthage/Build/DataKit.xcframework
      - framework: Carthage/Build/GemCommonsKit.xcframework
      - framework: Carthage/Build/ObjCCommonsKit.xcframework
    scheme:
     gatherCoverageData: true 
  ASN1KitTests:
    type: bundle.unit-test
    platform: [macOS,iOS]
    info:
      path: Resources/ASN1Kit_Tests_Info.plist
    sources:
      - path: Tests/ASN1KitTests
    dependencies:
      - target: ASN1Kit_${platform}
      - framework: Carthage/Build/Nimble.xcframework
buildImplicitDependencies: true
