////
Execute `make readme` after editing <project_root>/README.adoc
////
:testdir: Tests

= ASN1Kit

ASN.1 Decoder for Swift


== API Documentation

Generated API docs are available at https://swiftpackageindex.com/gematik/ASN1Kit/documentation/.


== Overview

This library can be used for ASN.1 (Abstract Syntax Notation One) encoding/decoding
using distinguished encoding rules (DER) according to the ITU-T X.690

For more info, please find the complete https://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf[X.690-0207.pdf]
specification.


== Getting Started

ASN1Kit requires Swift 5.1.

=== Setup for integration

==== Carthage
Put this in your `Cartfile`:

    github "gematik/ASN1Kit" ~> 1.0

=== Setup for development

You will need https://bundler.io/[Bundler], https://github.com/yonaskolb/XcodeGen[XcodeGen]
and https://fastlane.tools[fastlane] to conveniently use the established development environment.

. Checkout (and build) dependencies and generate the xcodeproject
[source,Shell]
$ make setup

. Build the project
[source,Shell]
$ make cibuild


== Code Samples

Use `ASN1Decoder.decode(asn1:)` to decode serialized data:

[source,swift]
----
include::{testDir}/ASN1KitTests/encodable/BitStringASN1EncodingTest.swift[tags=decodeSerializedData,indent=0]
----

Construct an `ASN1Object` of your choice and serialize it:

[source,swift]
----
include::{testDir}/ASN1KitTests/encodable/ArrayExtASN1EncodingTest.swift[tags=constructAndEncode,indent=0]
----

ASN.1-encode Swift primitives and extract the encoded value(s):

[source,swift]
----
include::{testDir}/ASN1KitTests/encodable/IntExtASN1EncodingTest.swift[tags=encodeSwiftPrimitives,indent=0]
----

Extract the tag of the first element of a constructed `ASN1Object`:

[source,swift]
----
include::{testDir}/ASN1KitTests/ASN1ConstructedEncodingTest.swift[tags=encodeSwiftPrimitives2,indent=0]
----


== License
 
Apache License Version 2.0
 
See link:./LICENSE[LICENSE].