#!/bin/sh

# scripts/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -ev

cd "$(dirname "$0")/.."

scripts/bootstrap

bundle exec fastlane setup

echo "==> Project is now ready to go!"
